Dev_mythip@capgemini.com_17Dec_ForGitSync/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev_mythip@capgemini.com_17Dec_ForGitSync/src/objects/Salary__c.object
<CustomObject>
    <label>Salary</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Salary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Dev_mythip@capgemini.com_17Dec_ForGitSync/src/classes/Employee.cls
public with sharing class Employee {
	public Integer empId{get;set;}
	public String empName{get;set;}
	public String empAddress{get;set;}
	public String empDepartment{get;set;}
	public String empSalary{get;set;}
	
	public Pagereference redirect(){
		String s=[select Employee__c.Name__c from Employee__c where Employee__c.Name__c=:empName].Name__c;
		if(s!=null)
		{
		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'my error msg');
		ApexPages.addMessage(myMsg);
		return null;
		}
		else{
		Employee__c  e=new Employee__c();
		e.Id__c=empId;
		e.Name__c=empName;
		e.Address__c=empAddress;
		e.Department__c=empDepartment;
		e.Salary__c=empSalary;
		insert e;
		Pagereference testPage = new Pagereference('/apex/EmployeeDetailsSuccessfull');
		return testPage;
		}
	}
	
	public void clear(){
		empId=null;
		empName=null;
		empAddress=null;
		empDepartment=null;
		empSalary=null;
	}
}