Dev_mythip@capgemini.com_17Dec_ForGitSync/src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Bonus_Amount__c</fullName>
        <label>Bonus Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salary__c</fullName>
        <label>Salary</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>Employee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dev_mythip@capgemini.com_17Dec_ForGitSync/src/objects/Salary__c.object
<CustomObject>
    <label>Salary</label>
    <nameField>
        <displayFormat>PAY-{0000}</displayFormat>
        <label>Salary Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salaries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Dev_mythip@capgemini.com_17Dec_ForGitSync/src/classes/SaveEmployeeDetails.cls
public with sharing class SaveEmployeeDetails{

    public String empName{get;set;}
    
    public Decimal bonus{get;set;}
    
    public String department{get;set;}
    
    public String salary{get;set;}
    
    public void saveEmp(){
        Employee__c emp=new Employee__c();
        emp.Name__c=empName;
        emp.Bonus_Amount__c=bonus;
        emp.Department__c=department;
        emp.Salary__c=salary;
        insert emp;
    }

}